### ISSUE TITLE
Fatal error: an empty sequence is not allowed as the third argument of key(); collectCounts.xsl

### ISSUE THREAD

**Issue by aidanreilly** [dita-semia/org.dita-semia.topic-num#1]
Hi @PStellmann, 

Me again :) I hope you are well. I'd like to use your table/figure numbering plugin in our build. It looks really useful. I'm trying to make it work in a base DITA OT 2.5.4. 

In plugin.xml, I added the following import statments: 

```
	<feature extension="dita.conductor.lib.import"		file="lib/ant-contrib-1.0b3.jar"/>
	<feature extension="dita.conductor.lib.import"		file="lib/RasterizerTask.jar"/>
	<feature extension="dita.conductor.lib.import"		file="lib/batik-all-1.8.jar"/>
	<feature extension="dita.conductor.lib.import"		file="lib/xml-apis-ext.jar"/>
```

Then, I run: 

`dita -f xhtml -i C:/Users/jreillai/dita-ot-2.5.4/plugins/org.dita-semia.topic-num/test/topic-num-test.ditamap -o out -Ddita-semia.topic-num.activate=true -Dargs.xsl=plugins/org.dita-semia.topic-num/xsl/xhtml/dita2xhtml.xsl`

This outputs successfully. 

When i run the following on the OT test map, I get an error: 

`dita -f xhtml -i C:\Users\jreillai\dita-ot-2.5.4\docsrc\userguide.ditamap -o out -Ddita-semia.topic-num.activate=true -Dargs.xsl=plugins/org.dita-semia.topic-num/xsl/xhtml/dita2xhtml.xsl`

> Error: Fatal error during transformation using C:\Users\jreillai\dita-ot-2.5.4\plugins\org.dita-semia.topic-num\xsl\processMap.xsl: An empty sequence is not allowed as the third argument of key(); SystemID: file:/C:/Users/jreillai/dita-ot-2.5.4/plugins/org.dita-semia.topic-num/xsl/collectCounts.xsl; Line#: 20; Column#: -1

Any ideas why this plugin doesn't work as expected?

**Comment by patrickleevers** [comment]
Hi Aidan,
I think we have a Patrik/ck confusion here! This plugin is actually Patrik Stellman’s (PStellmann). I’ve used it, I’ve had some problems with it and I’ve been in touch with Patrik about them, but I’m puzzled about how my name came to be associated with it?

Best wishes
Pat Leevers (patrickleevers)

**Comment by aidanreilly** [comment]
oops! sorry Pat. Amended above.

**Comment by PStellmann** [comment]
Hi Adian,

I could reproduce the error you described and made a fix by ignoring referenced files with processing-role="resource-only".

Now to transformation to xhtml works but I noticed two other issues:
1. processing the ditamap only rarely the numbers were generated - probably because I'm trying to insert the number in a title element which is missing most of the time here.
2. processing the bookmap the numbers are not currect since there is no handling of parts, yet. Thus, only the chapters are numbered independantly in each part.

Let me know if any of these issues is relevant for you and I might take a look at those as well.

Regards,
Patrik

**Comment by aidanreilly** [comment]
Thanks for the swift response Patrik! Incorporating your change, I now see the following: 

> Error: Fatal error during transformation using C:\Users\jreillai\dita-ot-2.5.4\plugins\org.dita-semia.topic-num\xsl\processMap.xsl: Cannot write more than one result document to the same URI: file:/C:/WINDOWS/TEMP/temp20200201120657207/release-notes/index.dita.topic-num.tmp; SystemID: file:/C:/Users/jreillai/dita-ot-2.5.4/plugins/org.dita-semia.topic-num/xsl/processMap.xsl; Line#: 104; Column#: -1

when I run: 

`dita -f xhtml -i C:\Users\jreillai\dita-ot-2.5.4\docsrc\userguide.ditamap -o out -Ddita-semia.topic-num.activate=true -Dargs.xsl=plugins/org.dita-semia.topic-num/xsl/xhtml/dita2xhtml.xsl`

Is this occuring because we have multiple instances of `id="ID"` in the dita files?

**Comment by PStellmann** [comment]
The error is caused by trying to process the same topic file twice. This occurs when there are multiple topicrefs for the same file.

When there are "real" multiple topicrefs to the same topic there is a problem since the topic would have multiple numbers. I don't have any solution for this scenario yet.

However, for the userguide this is not the case so I tried to ignore some types of topicrefs that seem not to be relevant for the numbering:
- with html format
- within reltable
